import Head from 'next/head'

import styles from '../styles/Home.module.css'
import 'antd/dist/antd.css'

import { Button, Space, DatePicker, Card } from 'antd';
import { CiCircleFilled } from '@ant-design/icons';
import UserLogin from '../components/userLogin';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.bankofbaroda.in%2F-%2Fmedia%2Fproject%2Fbob%2Fcountrywebsites%2Findia%2Ficons%2Fbankofbaroda-accounts.svg%3Fiar%3D0%26hash%3DD11D258092109F4F96E8F910BB62513C&imgrefurl=https%3A%2F%2Fwww.bankofbaroda.in%2F&tbnid=PWjq3qxlEpdoRM&vet=12ahUKEwj527iRpYf5AhUMC-wKHeWzCqoQMygiegUIARCsAg..i&docid=1yYtACev3j8CtM&w=800&h=800&itg=1&q=bank%20image&ved=2ahUKEwj527iRpYf5AhUMC-wKHeWzCqoQMygiegUIARCsAg" />
      </Head>

      <UserLogin />

    </div>
  )
}
